apiVersion: v1
kind: ConfigMap
metadata:
  name: cow-farm-config
  namespace: aadhi-bhairava-cow-farm
data:
  NODE_ENV: "production"
  PORT: "5000"
  CORS_ORIGIN: "https://www.aadhibhairavacowfarm.com"
  NEXT_PUBLIC_API_URL: "https://api.aadhibhairavacowfarm.com"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET_NAME: "cowfarm-assets"
