apiVersion: v1
kind: Secret
metadata:
  name: cow-farm-secrets
  namespace: aadhi-bhairava-cow-farm
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:YOUR_DB_PASSWORD@postgres-service:5432/cowfarm_db?schema=public"
  JWT_SECRET: "YOUR_PRODUCTION_JWT_SECRET_MIN_32_CHARS"
  JWT_REFRESH_SECRET: "YOUR_PRODUCTION_JWT_REFRESH_SECRET_MIN_32_CHARS"
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
